# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jose Perez Prol
email: hernani84@gmail.com
phone: (786) 399-9615
description: > # this means to ignore newlines until "baseurl:"
  I enjoy building web applications & playing with my cat.
  I'm a coffee & carft beer lover. Workign Sysadmin @vertilux. Web apps developer mostly with Ruby on Rails. Mad about Linux and System Admnistration.
  Currently working towards the Linux Foundation System Administrator Certification and SQL: Analyzing Business Metrics. Docker containers
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# social media
facebook_username: jose.perezprol
twitter_username: hernani84
github_username: lepepe
instagram_username: hernani84

# Build settings
markdown: kramdown
