# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jose Perez Prol (a.k.a. Le Pepe)
email: hernani84@gmail.com
phone: (305) 833-8445
description: > # this means to ignore newlines until "baseurl:"
  Passionate about crafting web applications and APIs, my expertise lies primarily in utilizing Ruby on Rails and Flask
  to bring innovative digital solutions to life.

  When I'm not immersed in code, you can find me savoring the perfect cup of coffee or exploring the world of craft beer.
  My love for technology extends to my deep enthusiasm for Linux, DevOps practices, and the intricacies of SQL.

  I proudly hold the certification of a Linux Admin, awarded by the esteemed Foundation System Administrator Certification.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lepepe.github.io/" # the base hostname & protocol for your site

# Social media
twitter_username: hernani84
github_username: lepepe
instagram_username: hernani84

# Build settings
markdown: kramdown

jekyll_admin:
  hidden_links:
    #- posts
    #- pages
    #- staticfiles
    #- datafiles
    #- configuration
  homepage: "pages"

# Portfolio
collections:
  portfolio:
    output: true
