# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jose Perez Prol (a.k.a. Le Pepe)
email: hernani84@gmail.com
phone: (305) 833-8445
description: > # this means to ignore newlines until "baseurl:"
  Passionate about crafting robust web applications and APIs, I specialize in building solutions with Ruby on Rails, Flask, and FastAPI. 
  My journey in technology has expanded into the world of data engineering, where I leverage tools like Qlik Replicate and orchestrate 
  workflows with Apache Airflow. I'm currently diving deep into Apache Spark to enhance my data processing capabilities. Beyond the keyboard, 
  you'll find me exploring the world of craft beer, sipping a great cup of coffee, and maintaining my certified Linux Admin status with 
  a strong focus on DevOps practices and SQL.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lepepe.github.io/" # the base hostname & protocol for your site

# Social media
twitter_username: hernani84
github_username: lepepe
instagram_username: hernani84

# Build settings
markdown: kramdown

jekyll_admin:
  hidden_links:
    #- posts
    #- pages
    #- staticfiles
    #- datafiles
    #- configuration
  homepage: "pages"

# Portfolio
collections:
  portfolio:
    output: true
